version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo Building the Spring Boot application...
      - chmod +x ./gradlew
      - ./gradlew clean build

  post_build:
    commands:
      - echo Building the Docker image...
      - docker build -t testwar .
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag testwar:latest $ECR_REGISTRY/testwar:latest
      - docker push $ECR_REGISTRY/testwar:latest

artifacts:
  files:
    - build/libs/*.jar
