spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: 'true'
    show-sql: 'false'
    hibernate:
      ddl-auto: validate
      format_sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://test-db.cf9tl9askmqc.ap-northeast-2.rds.amazonaws.com:3306/basicDB?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: '!admin0123'

logging:
  config: classpath:logback-spring.xml

server:
  tomcat:
    basedir: /logs001                        # access log를 저장할 base directory 지정
    accesslog:
      enabled: true                         # access log 저장 여부 (default: false)
      directory: access                       # access log를 저장할 상세 directory (base directory에 기반한) (default: logs)
      pattern: '%h %l %u %t "%r" %s %b %D'  # access log 출력 패턴
      prefix: access                        # access log 파일이름 prefix
      suffix: .log                          # access log 파일이름 suffix (확장자 포함)
      rotate: true                          # access log rotation 여부
      rename-on-rotate: true                # rotation 시, 새로운 이름 지정 여부 (rotate 될 때의 날짜명이 로그 파일이름에 찍힘)
